GET {{HTTP_HOST}}/ranks

POST {{HTTP_HOST}}/ranks/create
Content-Type: application/json
Authorization: Token {{HTTP_TOKEN}}

{
  "rank": "admin",
  "description": "Usuario con permisos de administrador"
}

PUT {{HTTP_HOST}}/ranks/update
Content-Type: application/json
Authorization: Token {{HTTP_TOKEN}}

{
  "id": 13,
  "rank": "dafault",
  "description": "Usuario inicial de la aplicacion"
}

DELETE {{HTTP_HOST}}/ranks/delete
Content-Type: application/json
Authorization: Token {{HTTP_TOKEN}}

{
  "id": 13
}
